# Generated by Django 4.0 on 2021-12-16 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=50, verbose_name='Nombre corto')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Area docentes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('first_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre completo')),
                ('job', models.CharField(choices=[('0', 'Sistemas Operativos'), ('1', 'Matemática Aplicada'), ('2', 'Modelado de Sistemas'), ('3', 'Programación II'), ('4', 'Base de Datos'), ('5', 'Practica Profesionalizante I')], max_length=50, verbose_name='Materia')),
                ('avatar', models.ImageField(blank=True, upload_to='registro', verbose_name='Imagen')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.departamentodocente')),
                ('habilidad', models.ManyToManyField(to='registro.Habilidad')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
    ]
