# Generated by Django 4.0 on 2021-12-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentodocente',
            options={'ordering': ['name'], 'verbose_name': 'Area', 'verbose_name_plural': 'Area docente'},
        ),
        migrations.RenameField(
            model_name='empleadodocente',
            old_name='job',
            new_name='materia',
        ),
    ]
