# Generated by Django 4.0 on 2021-12-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_departamentodocente_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilidad',
            new_name='HabilidadDocente',
        ),
    ]
