# Generated by Django 4.0 on 2021-12-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_rename_habilidad_habilidaddocente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoNoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=50, verbose_name='Nombre corto')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Area B',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HabilidadNoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.AlterModelOptions(
            name='departamentodocente',
            options={'ordering': ['name'], 'verbose_name': 'Area', 'verbose_name_plural': 'Area A'},
        ),
        migrations.CreateModel(
            name='EmpleadoNoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('first_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre completo')),
                ('oficina', models.CharField(choices=[('0', 'Coordinación'), ('1', 'Limpieza'), ('2', 'Preceptoría'), ('3', 'Dirección'), ('4', 'Mantenimiento'), ('5', 'Otro')], max_length=50, verbose_name='Materia')),
                ('avatar', models.ImageField(blank=True, upload_to='registro', verbose_name='Imagen')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.departamentodocente')),
                ('habilidad', models.ManyToManyField(to='registro.HabilidadDocente')),
            ],
            options={
                'verbose_name': 'No Docente',
                'verbose_name_plural': 'No Docentes',
            },
        ),
    ]
