# Generated by Django 4.0 on 2021-12-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_departamentonodocente_habilidadnodocente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidaddocente',
            options={'verbose_name': 'Habilidad docente', 'verbose_name_plural': 'Habilidades docentes'},
        ),
        migrations.AlterModelOptions(
            name='habilidadnodocente',
            options={'verbose_name': 'Habilidad no docente', 'verbose_name_plural': 'Habilidades no docentes'},
        ),
    ]
