# Generated by Django 4.0 on 2021-12-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_habilidaddocente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadonodocente',
            name='oficina',
            field=models.CharField(choices=[('0', 'Coordinación'), ('1', 'Limpieza'), ('2', 'Preceptoría'), ('3', 'Dirección'), ('4', 'Mantenimiento'), ('5', 'Otro')], max_length=50, verbose_name='Oficina'),
        ),
    ]
