# Generated by Django 4.0 on 2021-12-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_delete_departamentonodocente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
