# Generated by Django 4.0 on 2021-12-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_materia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
