# Generated by Django 4.0 on 2021-12-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_materia_oficina_rename_habilidaddocente_habilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadodocente',
            name='asignatura',
            field=models.ManyToManyField(to='registro.Materia'),
        ),
    ]
