# Generated by Django 4.0 on 2021-12-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_empleadodocente_asignatura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oficina',
        ),
        migrations.RemoveField(
            model_name='empleadodocente',
            name='asignatura',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
